name: EXSi_60_Customized_Net-r8101_linux_env
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: 'EXSi_60_Customized'
      driver:
        description: 'Driver Name'
        required: true
        default: 'net-r8101'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
           python-version: '3.7' 
      - name: Python Check
        shell: bash
        run: |
          which python && which pip3
          python --version && pip3 --version
          
      - name: Install Powershell
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update && sudo apt-get install -y powershell
          
      - name: Download ESXi-Customizer-PS Script and base image
        shell: bash
        run: |
          wget -O ESXi-Customizer-PS-2.9.0.zip https://github.com/VFrontDe-Org/ESXi-Customizer-PS/archive/refs/tags/2.9.0.zip
          unzip ESXi-Customizer-PS-2.9.0.zip && cd ESXi-Customizer-PS-2.9.0
          pwd
          
      - name: Download base image
        shell: pwsh
        run: |
          cd ESXi-Customizer-PS-2.9.0
          Add-EsxSoftwareDepot https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/vmw-depot-index.xml
          Export-ESXImageProfile -ImageProfile "ESXi-6.0.0-20200204001-standard" -ExportToBundle -filepath ESXi-6.0.0-20200204001-standard.zip
          
      - name: Install VMware.PowerCli
        shell: pwsh
        run: |
          $PSVersionTable
          Install-Module -Name VMware.PowerCLI -Force -AcceptLicense
          Get-Module -Name VMware.PowerCli -ListAvailable
          pip3 install six psutil lxml pyopenssl
          
      
      - name: Use Script Customize Exsi ISO
        shell: pwsh
        run: |
          cd ESXi-Customizer-PS-2.9.0
          ./ESXi-Customizer-PS.ps1 -izip ./ESXi-6.0.0-20200204001-standard.zip -nsc -vft -log exsi.log -load sata-xahci,${{ github.event.inputs.driver }} -ipname ${{ github.event.inputs.tag }}_${{ github.event.inputs.driver }} -outDir .
      
      - name: Rename iso
        shell: bash
        run: |
          cd ESXi-Customizer-PS-2.9.0
          dir .
          mv ../ESXi-Customizer-PS-2.9.0\\EXSi_60_Customized_net-r8101.iso EXSi_60_Customized_net-r8101.iso
       
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          name: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            ESXi-Customizer-PS-2.9.0/${{ github.event.inputs.tag }}_${{ github.event.inputs.driver }}.iso
